server:
  port: 80
  servlet:
    context-path: /chatbot

logging:
  file: LOGS/CHATBOT.LOG
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    
#  pattern:
#    console: '%d %-5level %logger : %msg%n'
#    file: '%d %-5level [%thread] %logger : %msg%n'

